{% set name = "torchtext" %}
{% set version = "0.8.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  git_url: https://github.com/pytorch/text.git
  git_rev: v{{ version }}
  patches:
    # 01xx - patch is specific to open-ce and will always be carried forward and not upstreamed
    - 0101-disable-tcmalloc.patch

build:
  number: 7
  string: py{{ python | replace(".", "") }}_{{ PKG_BUILDNUM }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake {{ cmake }}
    - make
    - patch
    # Use pins to control cos6/cos7 match
    - libgcc-ng  {{ libgcc }}
    - libstdcxx-ng  {{ libstdcxx }}
  host:
    - python {{ python }}
    - pytorch-base     {{ pytorch }}
    # Use pins to control cos6/cos7 match
    - libgcc-ng  {{ libgcc }}
    - libstdcxx-ng  {{ libstdcxx }}
  run:
    - numpy {{ numpy }}
    - python {{ python }}
    - pytorch-base {{ pytorch }}
    - requests {{ requests }}
    - tqdm {{ tqdm }}
    - sentencepiece {{ sentencepiece }}

test:
  imports:
    - torchtext
    - torchtext.data
    - torchtext.datasets

about:
  home: https://github.com/pytorch/text
  license: BSD
  license_family: BSD
  license_file: LICENSE
  summary: Text utilities and datasets for PyTorch
  description: Text utilities and datasets for PyTorch
  doc_url: https://torchtext.readthedocs.io/en/latest/
  dev_url: https://github.com/pytorch/text/

extra:
  recipe-maintainers:
    - open-ce/open-ce-dev-team
