recipes:
{% if build_type == 'cuda' and cudatoolkit == '11.2' %}
  - name : torchtext-base
    path : text-0.11/recipe

  - name : torchtext-meta
    path : text-0.11/variants
{% else %}
  - name : torchtext-base
    path : text-0.14/recipe

  - name : torchtext-meta
    path : text-0.14/variants
{% endif %}
